language: python

notifications:
  email: false

python:
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"

# command to install dependencies
install:
  - pip install flake8

# command to run tests
script:
  - flake8 chatimusmaximus
