version: "0.1.1"

display:
    command_line: "user@chatimus ~$ "

communication_port: 'tcp://localhost:5599'

services:

    irc:

        twitch:
            # I use this site to get oauth_token 
            # https://twitchapps.com/tmi/
            # use this format: `oauth:asdasd234asd234ad234asds23`
            oauth_token: ""
            # this will be your twitch channel
            channel: ""
            # I believe this has to be your twitch acct name
            nick: ""
            # TODO: add in default handeling
            default_socket_address: ""
            connect: false
            display_missing: true

    xmpp:

        livecoding:
            # this MUST be your livecode name
            name: ""
            # this can be your profile password
            password: ""
            bot_nick: ""
            room: ""
            # TODO: add in default handeling
            default_socket_address: ""
            connect: false
            display_missing: true

    # socket_io is hardcoded for watchpeople code
    # feel free to yell at me about that on github
    socket_io:

        watchpeoplecode:
            channel: ""
            # TODO: add in default handeling
            default_socket_address: ""
            connect: false
            display_missing: true
    
    # youtube is special.
    youtube:
        # FIXME: add in default handeling
        # default_socket_address: ""
        # connect: false
        
        # must install selenium. Don't need OAuth credentials
        javascript_scraper:
             # NOTE: only pass in channel id if you want to connect chat to your 
             # permenant landing page
            channel_id: ""
            youtube_url: ""
            # FIXME
            display_missing: true
        
        # go to goole developers console. Create an app and request
        # YouTube Data API v3 access. Create and download OAuth credentials
        # and put the filepath info in `client_secrets_file`
        api_connect:
            client_secrets_file: ""
            # FIXME
            display_missing: true
